# Generated by Django 6.1 on 2026-09-03 15:13

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyConstituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assemblyConstituencyName', models.CharField(max_length=100)),
                ('isExist', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('death_date', models.DateTimeField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Sikh', 'Sikh'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist')], max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('caste_category', models.CharField(blank=True, choices=[('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OC', 'OC')], max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, null=True)),
                ('fathers_Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Spouse_Name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Highest_Education', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('University', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('presentaddress', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('premanentaddress', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('Email_address', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('Mobile', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('children', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('person_photo', models.ImageField(blank=True, null=True, upload_to=person.models.upload_person_photo)),
                ('fathers_image', models.ImageField(blank=True, null=True, upload_to=person.models.upload_father_photo)),
                ('spouse_image', models.ImageField(blank=True, null=True, upload_to=person.models.upload_spouse_photo)),
                ('voice_sample', models.FileField(blank=True, null=True, upload_to=person.models.upload_voice_sample)),
                ('isPresent', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
