# Generated by Django 6.1 on 2026-09-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assembly', '0003_initial'),
        ('city', '0003_initial'),
        ('district', '0002_initial'),
        ('party', '0007_remove_party_partysymbol_party_partyflag'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyconstituency',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.state'),
        ),
        migrations.AddField(
            model_name='mla',
            name='birth_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_city', to='city.city'),
        ),
        migrations.AddField(
            model_name='mla',
            name='birth_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_district', to='district.district'),
        ),
        migrations.AddField(
            model_name='mla',
            name='birth_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_state', to='state.state'),
        ),
        migrations.AddField(
            model_name='mla',
            name='constituency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assembly.assemblyconstituency'),
        ),
        migrations.AddField(
            model_name='mla',
            name='party',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party'),
        ),
        migrations.AlterUniqueTogether(
            name='assemblyconstituency',
            unique_together={('assemblyConstituencyName',)},
        ),
        migrations.AlterUniqueTogether(
            name='mla',
            unique_together={('name',)},
        ),
    ]
