# Generated by Django 6.1 on 2026-09-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_initial'),
        ('district', '0002_initial'),
        ('loksabha', '0002_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assemblyconstituency',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assemblyconstituency',
            constraint=models.UniqueConstraint(fields=('state', 'loksabhaConstituency', 'assemblyConstituencyName'), name='unique_assemblyconstituency'),
        ),
    ]
