# Generated by Django 6.1 on 2026-09-04 06:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_alter_assemblyconstituency_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyConstituencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('assemblyConstituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assembly.assemblyconstituency')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assemblyConstituency',), name='unique_boundary_per_assembly_constituency')],
            },
        ),
    ]
