# Generated by Django 6.1 on 2026-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0007_remove_mla_birth_district_remove_mla_birth_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyconstituency',
            name='reservationCategory',
            field=models.CharField(choices=[('GEN', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], default='GEN', max_length=5),
        ),
    ]
