# Generated by Django 6.1 on 2026-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0008_assemblyconstituency_reservationcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyconstituency',
            name='reservationCategory',
            field=models.CharField(choices=[('GEN', 'GEN'), ('SC', 'SC'), ('ST', 'ST')], default='GEN', max_length=10),
        ),
    ]
