# Generated by Django 6.1 on 2026-09-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0002_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.state'),
        ),
        migrations.AddField(
            model_name='citymap',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.AddConstraint(
            model_name='citymap',
            constraint=models.UniqueConstraint(fields=('city',), name='unique_boundary_per_city'),
        ),
    ]
