# Generated by Django 6.1 on 2026-09-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='state.state'),
        ),
        migrations.AddField(
            model_name='districtmap',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'districtName')},
        ),
        migrations.AddConstraint(
            model_name='districtmap',
            constraint=models.UniqueConstraint(fields=('district',), name='unique_boundary_per_district'),
        ),
    ]
