# Generated by Django 6.1 on 2026-09-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlc',
            name='birth_district',
        ),
        migrations.RemoveField(
            model_name='mlc',
            name='birth_state',
        ),
    ]
