# Generated by Django 6.1 on 2026-09-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panchayat', '0001_initial'),
        ('state', '0001_initial'),
        ('taluk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayat',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.state'),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='taluk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taluk.taluk'),
        ),
        migrations.AddField(
            model_name='panchayatmap',
            name='panchayat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panchayat.panchayat'),
        ),
        migrations.AddConstraint(
            model_name='panchayat',
            constraint=models.UniqueConstraint(fields=('district', 'panchayatName'), name='unique_panchayat_per_district'),
        ),
        migrations.AddConstraint(
            model_name='panchayatmap',
            constraint=models.UniqueConstraint(fields=('panchayat',), name='unique_boundary_per_panchayat'),
        ),
    ]
