# Generated by Django 5.2 on 2025-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="candidate_inparty_period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partystatus",
                    models.CharField(
                        choices=[("Regional", "regional"), ("National", "national")],
                        max_length=30,
                    ),
                ),
                ("partyname", models.CharField(max_length=100)),
                (
                    "abbreviation",
                    models.CharField(max_length=20, null=True, unique=True),
                ),
                ("President", models.CharField(max_length=100, null=True)),
                ("founder", models.CharField(max_length=100, null=True)),
                ("chairperson", models.CharField(max_length=100, null=True)),
                ("founded_date", models.DateField()),
                ("headquarters", models.CharField(max_length=1000, null=True)),
                (
                    "party_symbol",
                    models.ImageField(
                        null=True, upload_to="Party/party_symbol/%Y-%m-%d/%H-%M-%S"
                    ),
                ),
                (
                    "founderPhoto",
                    models.ImageField(
                        null=True, upload_to="Party/founderPhoto/%Y-%m-%d/%H-%M-%S"
                    ),
                ),
                (
                    "chairpersonPhoto",
                    models.ImageField(
                        null=True, upload_to="Party/chairpersonPhoto/%Y-%m-%d/%H-%M-%S"
                    ),
                ),
                (
                    "PresidentPhoto",
                    models.ImageField(
                        null=True, upload_to="Party/PresidentPhoto/%Y-%m-%d/%H-%M-%S"
                    ),
                ),
            ],
        ),
    ]
