# Generated by Django 5.2 on 2025-05-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="party",
            old_name="founded_date",
            new_name="foundeddate",
        ),
        migrations.RenameField(
            model_name="party",
            old_name="party_symbol",
            new_name="partysymbol",
        ),
        migrations.AddField(
            model_name="party",
            name="party_color",
            field=models.CharField(
                choices=[
                    ("#FF9933", "BJP - Orange"),
                    ("#00A2E8", "INC - Blue"),
                    ("#000000", "CPI(M) - Black"),
                    ("#FF0000", "CPI - Red"),
                    ("#008000", "BSP - Green"),
                    ("#FFD700", "TMC - Yellow"),
                    ("#FF4500", "Shiv Sena - Saffron"),
                    ("#A52A2A", "DMK - Brown"),
                    ("#000080", "AIADMK - Navy Blue"),
                    ("#800080", "AAP - Purple"),
                    ("#FFFFFF", "None/Independent - White"),
                ],
                default="#FFFFFF",
                help_text="Select party color",
                max_length=7,
            ),
        ),
    ]
