# Generated by Django 5.2 on 2025-05-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0002_rename_founded_date_party_foundeddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="party_color",
            field=models.CharField(
                choices=[
                    ("#FF9933", "BJP - Orange"),
                    ("#00A2E8", "INC - Blue"),
                    ("#000000", "CPI(M) - Black"),
                    ("#FF0000", "CPI - Red"),
                    ("#008000", "BSP - Green"),
                    ("#FFD700", "TMC - Yellow"),
                    ("#FF4500", "Shiv Sena - Saffron"),
                    ("#A52A2A", "DMK - Brown"),
                    ("#000080", "AIADMK - Navy Blue"),
                    ("#800080", "AAP - Purple"),
                    ("#FFFF00", "TDP - Yellow"),
                    ("#008000", "JD(U) - Green"),
                    ("#00FF00", "JMM - Bright Green"),
                    ("#FF0000", "NPP - Red"),
                    ("#00CED1", "ZPM - Turquoise"),
                    ("#DC143C", "NDPP - Crimson"),
                    ("#FF4500", "SKM - Red"),
                    ("#FFA500", "AINRC - Saffron"),
                    ("#FFFFFF", "None/Independent - White"),
                ],
                default="#FFFFFF",
                help_text="Select party color",
                max_length=7,
            ),
        ),
    ]
