# Generated by Django 5.2 on 2025-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0003_alter_party_party_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="PresidentPhoto",
            field=models.ImageField(
                null=True, upload_to="adhikar/party/PresidentPhoto"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="chairpersonPhoto",
            field=models.ImageField(
                null=True, upload_to="adhikar/party/chairpersonPhoto"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="founderPhoto",
            field=models.ImageField(null=True, upload_to="adhikar/party/founderPhoto"),
        ),
        migrations.AlterField(
            model_name="party",
            name="partysymbol",
            field=models.ImageField(null=True, upload_to="adhikar/party/partysymbol"),
        ),
    ]
