# Generated by Django 5.2 on 2025-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0004_alter_party_presidentphoto_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="party",
            constraint=models.UniqueConstraint(
                fields=("partyname",), name="unique_partyname"
            ),
        ),
    ]
