# Generated by Django 6.0 on 2026-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_party_unique_partyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='electionsymbol',
            field=models.ImageField(null=True, upload_to='adhikar/party/electionsymbol'),
        ),
    ]
