# Generated by Django 6.1 on 2026-08-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_party_electionsymbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='partysymbol',
        ),
        migrations.AddField(
            model_name='party',
            name='partyflag',
            field=models.ImageField(null=True, upload_to='adhikar/party/partyflag'),
        ),
    ]
