# Generated by Django 6.1 on 2026-09-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cm', '0001_initial'),
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cm',
            name='birth_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_district', to='district.district'),
        ),
    ]
