# Generated by Django 6.1 on 2026-09-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cm', '0002_initial'),
        ('party', '0007_remove_party_partysymbol_party_partyflag'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cm',
            name='birth_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_state', to='state.state'),
        ),
        migrations.AddField(
            model_name='cm',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_party', to='party.party'),
        ),
        migrations.AddField(
            model_name='cm',
            name='rulingstate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_ruling_state', to='state.state'),
        ),
        migrations.AddField(
            model_name='cm',
            name='rulingperiods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.cm_ruling_period'),
        ),
    ]
