# Generated by Django 6.0 on 2026-01-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('monsoon', 'monsoon'), ('winter', 'winter'), ('budget', 'budget')], max_length=10)),
                ('house', models.CharField(choices=[('loksabha', 'loksabha'), ('rajyasabha', 'rajyasabha'), ('both', 'both')], max_length=12)),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('season', 'house', 'year'), name='unique_session_season_house_year')],
            },
        ),
        migrations.CreateModel(
            name='SessionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='session_info.sessiondetails')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'number'), name='unique_phase_number_per_session')],
            },
        ),
    ]
