# Generated by Django 6.1 on 2026-09-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0003_initial'),
        ('district', '0002_initial'),
        ('loksabha', '0001_initial'),
        ('party', '0007_remove_party_partysymbol_party_partyflag'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loksabhaconstituency',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.state'),
        ),
        migrations.AddField(
            model_name='loksabhaconstituencymap',
            name='loksabhaConstituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loksabha.loksabhaconstituency'),
        ),
        migrations.AddField(
            model_name='loksabhamp',
            name='birth_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_city', to='city.city'),
        ),
        migrations.AddField(
            model_name='loksabhamp',
            name='birth_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_district', to='district.district'),
        ),
        migrations.AddField(
            model_name='loksabhamp',
            name='birth_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_state', to='state.state'),
        ),
        migrations.AddField(
            model_name='loksabhamp',
            name='constituency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loksabha.loksabhaconstituency'),
        ),
        migrations.AddField(
            model_name='loksabhamp',
            name='party',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party'),
        ),
        migrations.AddConstraint(
            model_name='loksabhaconstituency',
            constraint=models.UniqueConstraint(fields=('state', 'district', 'loksabhaConstituencyName'), name='unique_loksabhaconstituency'),
        ),
        migrations.AddConstraint(
            model_name='loksabhaconstituencymap',
            constraint=models.UniqueConstraint(fields=('loksabhaConstituency',), name='unique_boundary_per_constituency'),
        ),
        migrations.AlterUniqueTogether(
            name='loksabhamp',
            unique_together={('name',)},
        ),
    ]
