# Generated by Django 6.1 on 2026-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loksabha', '0003_remove_loksabhamp_birth_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loksabhaconstituency',
            name='reservationCategory',
            field=models.CharField(choices=[('GEN', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], default='GEN', max_length=5),
        ),
    ]
