# Generated by Django 6.1 on 2026-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loksabha', '0004_loksabhaconstituency_reservationcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loksabhaconstituency',
            name='reservationCategory',
            field=models.CharField(choices=[('GEN', 'GEN'), ('SC', 'SC'), ('ST', 'ST')], default='GEN', max_length=10),
        ),
    ]
