# Generated by Django 6.1 on 2026-09-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0007_remove_party_partysymbol_party_partyflag'),
        ('rajyasabha', '0001_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rajyasabhamp',
            name='birth_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_birth_state', to='state.state'),
        ),
        migrations.AddField(
            model_name='rajyasabhamp',
            name='party',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.party'),
        ),
        migrations.AddField(
            model_name='rajyasabhamp',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.state'),
        ),
        migrations.AlterUniqueTogether(
            name='rajyasabhamp',
            unique_together={('name',)},
        ),
    ]
