# Generated by Django 6.1 on 2026-09-03 15:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
        ('panchayat', '0001_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villageName', models.CharField(max_length=100)),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='district.district')),
                ('panchayat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panchayat.panchayat')),
                ('state', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='state.state')),
            ],
        ),
        migrations.CreateModel(
            name='VillageMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_properties', models.JSONField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='village.village')),
            ],
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(fields=('district', 'villageName'), name='unique_village_per_district'),
        ),
        migrations.AddConstraint(
            model_name='villagemap',
            constraint=models.UniqueConstraint(fields=('village',), name='unique_boundary_per_village'),
        ),
    ]
