# Generated by Django 6.1 on 2026-09-03 15:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(max_length=50, unique=True)),
                ('capital', models.CharField(blank=True, default='', max_length=50)),
                ('Status', models.CharField(choices=[('State', 'State'), ('UT', 'UT')], default='State', max_length=6)),
                ('abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('oldname', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Statename',), name='unique_Statename')],
            },
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formationdate', models.CharField(blank=True, max_length=100, null=True)),
                ('areasqkm', models.IntegerField(blank=True, default=None, null=True)),
                ('densitysqkm', models.IntegerField(blank=True, default=None, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_area_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalpopulation', models.IntegerField(blank=True, default=None, null=True)),
                ('malepopulation', models.IntegerField(blank=True, default=None, null=True)),
                ('femalepopulation', models.IntegerField(blank=True, default=None, null=True)),
                ('census_year', models.IntegerField(choices=[(2011, '2011')], default=2011)),
                ('DecadalGrowthRate', models.IntegerField(blank=True, default=None, null=True)),
                ('LiteracyRate', models.IntegerField(blank=True, default=None, null=True)),
                ('femtomaleSexRatio', models.CharField(max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'census_year'), name='unique_entity_census_year')],
            },
        ),
        migrations.CreateModel(
            name='StateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_properties', models.JSONField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state.state')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('state',), name='unique_boundary_per_state')],
            },
        ),
    ]
