# Generated by Django 5.2 on 2025-05-25 15:30

import django.db.models.deletion
import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("area_pop", "0006_alter_districts_districtname_and_more"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="executive_leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("dob", models.DateTimeField(blank=True, null=True)),
                ("death_date", models.DateTimeField(blank=True, null=True)),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Hindu", "Hindu"),
                            ("Muslim", "Muslim"),
                            ("Sikh", "Sikh"),
                            ("Christian", "Christian"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("caste", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "caste_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OBC", "OBC"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("OC", "OC"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "fathers_Name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Spouse_Name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Highest_Education",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "University",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", max_length=600, null=True),
                ),
                (
                    "Email_address",
                    models.EmailField(
                        blank=True, default="", max_length=100, null=True
                    ),
                ),
                (
                    "Mobile",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("children", models.CharField(blank=True, max_length=100, null=True)),
                ("extra_info", models.TextField(blank=True, null=True)),
                (
                    "person_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=person.models.upload_person_photo,
                    ),
                ),
                (
                    "fathers_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=person.models.upload_father_photo,
                    ),
                ),
                (
                    "spouse_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=person.models.upload_spouse_photo,
                    ),
                ),
                (
                    "leader_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pm", "pm"),
                            ("president", "president"),
                            ("vicepresident", "vicepresident"),
                            ("leader", "leader"),
                            ("opp_leader", "opp_leader"),
                            ("speaker", "speaker"),
                            ("dep_speaker", "dep_speaker"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_present",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "birth_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_birth_city",
                        to="area_pop.city",
                    ),
                ),
                (
                    "birth_district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_birth_district",
                        to="area_pop.districts",
                    ),
                ),
                (
                    "birth_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_birth_state",
                        to="area_pop.state",
                    ),
                ),
                (
                    "ruling_periods",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="par_exc_leaders_period",
                        to="person.ruling_period",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="parliament_leader",
            fields=[
                (
                    "executive_leader_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="executive_leaders.executive_leader",
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("loksabha", "loksabha"),
                            ("rajyasabha", "rajyasabha"),
                        ],
                        default="loksabha",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("executive_leaders.executive_leader",),
        ),
    ]
