# Generated by Django 5.2 on 2025-05-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("area_pop", "0006_alter_districts_districtname_and_more"),
        ("executive_leaders", "0001_initial"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="executive_leader",
            new_name="ExecutiveLeader",
        ),
        migrations.RenameModel(
            old_name="parliament_leader",
            new_name="ParliamentLeader",
        ),
        migrations.RenameField(
            model_name="parliamentleader",
            old_name="executive_leader_ptr",
            new_name="executiveleader_ptr",
        ),
    ]
